name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache cosmocc-4.0.2
        uses: actions/cache@v4
        with:
          path: cosmocc-4.0.2
          key: ${{ runner.os }}-cosmocc-4.0.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake unzip wget

      - name: Build
        shell: bash
        run: |
          set -Eeuo pipefail
          # Set up Cosmopolitan toolchain in PATH
          source env.sh

          # Configure and build with Ninja
          mkdir -p build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/cosmo.cmake
          ninja

      - name: Upload artifacts
        run: |
          set -Eeuo pipefail
          cd build/src
          
          cp ./z_pdb ./z_pdb.exe
          cp ./z_pdb ./z_pdb.zip
          
          gh release upload ${{ github.event.release.tag_name }} z_pdb z_pdb.com.dbg z_pdb.aarch64.elf z_pdb.exe z_pdb.zip
