name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache cosmocc-4.0.2
        uses: actions/cache@v4
        with:
          path: cosmocc-4.0.2
          key: ${{ runner.os }}-cosmocc-4.0.2

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.5.3
        with:
          packages: ninja-build cmake unzip wget
          version: 1.0

      - name: Build
        shell: bash
        run: |
          set -Eeuo pipefail
          # Set up Cosmopolitan toolchain in PATH
          source env.sh

          # Configure and build with Ninja
          mkdir -p build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/cosmo.cmake
          ninja

      - name: Upload artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -Eeuo pipefail
          cd build/src
          
          cp ./z_pdb ./z_pdb.exe
          cp ./z_pdb ./z_pdb.zip
          
          gh release upload ${{ github.event.release.tag_name }} z_pdb z_pdb.com.dbg z_pdb.aarch64.elf z_pdb.exe z_pdb.zip

      - name: Update release notes
        run: |
          set -Eeuo pipefail
          echo "${{ github.event.release.body }}\n" > notes.txt
          echo "${APPEND_BODY}" >> notes.txt
          gh release edit ${{ github.event.release.tag_name }} --notes-file notes.txt
        env:
          GH_TOKEN: ${{ github.token }}
          APPEND_BODY: |
            The following artifacts are the exact same file with a different extension, exe is recommended to support execution on Windows as well as Linux and MacOS:

            - z_pdb
            - z_pdb.exe
            - z_pdb.zip

            The .elf and .dbg files can be run with gdb on linux-x64 or linux-arm64
